# Generated by Django 5.0.6 on 2024-07-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
